<?xml version='1.0' encoding='windows-1251' ?>

<!DOCTYPE registrator [
	<!ELEMENT persons ( person ) >
	<!ELEMENT person ( name1, name2 ) >
	<!ELEMENT name1 ( #PCDATA ) >
	<!ELEMENT name2 ( #PCDATA ) >
	<!ATTLIST person key ID #REQUIRED >
]>

<persons>
	<person key="1">
		<name />
		<name1>Прізвище</name1>
		<name2>Прізвище</name2>
		<!-- ... -->
	</person>
	<person key="2">
		<name1>Прізвище</name1>
		<!-- ... -->
	</person>

</persons>